# Generated by Django 5.2.17 on 2026-09-19 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('properties', '0001_initial'),
        ('rates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('PEND', 'Pending'), ('CONF', 'Confirmed'), ('CHIN', 'Checked In'), ('CHOUT', 'Checked Out'), ('CANC', 'Cancelled'), ('NOSH', 'No Show')], default='PEND', max_length=5)),
                ('source', models.CharField(choices=[('WALK', 'Walk-In'), ('PHONE', 'Phone'), ('EMAIL', 'Email'), ('WEB', 'Website'), ('AGENT', 'Travel Agent')], max_length=6)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('adults', models.PositiveIntegerField(default=1)),
                ('children', models.PositiveIntegerField(default=0)),
                ('special_requests', models.TextField(blank=True)),
                ('deposit_required', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit_currency', models.CharField(default='MWK', max_length=3)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('primary_guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='people.person')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='properties.property')),
                ('rate_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='rates.rateplan')),
            ],
            options={
                'ordering': ['-check_in'],
            },
        ),
        migrations.CreateModel(
            name='ReservationRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate_per_night', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate_currency', models.CharField(default='MWK', max_length=3)),
                ('actual_check_in', models.DateTimeField(blank=True, null=True)),
                ('actual_check_out', models.DateTimeField(blank=True, null=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='reservations.reservation')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_rooms', to='properties.unit')),
            ],
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['property', 'status', 'check_in', 'check_out'], name='reservation_propert_d98ed8_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['reservation_number'], name='reservation_reserva_3144d8_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['primary_guest'], name='reservation_primary_07466b_idx'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('check_out__gt', models.F('check_in'))), name='reservation_checkout_after_checkin'),
        ),
        migrations.AlterUniqueTogether(
            name='reservationroom',
            unique_together={('reservation', 'unit')},
        ),
    ]
