# Generated by Django 5.2.17 on 2026-09-19 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folios', '0002_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourismLevyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('levy_percent', models.DecimalField(decimal_places=2, default=1.0, help_text='Default 1% per Tourism and Hotels Act', max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='levy_config', to='properties.property')),
            ],
            options={
                'verbose_name_plural': 'Tourism Levy Configurations',
            },
        ),
        migrations.CreateModel(
            name='TourismLevyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_charge_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('levy_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('levy_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('period_month', models.DateField(help_text='Month of levy applicability')),
                ('is_remitted', models.BooleanField(default=False)),
                ('remitted_at', models.DateTimeField(blank=True, null=True)),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levy_records', to='folios.folio')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
            options={
                'indexes': [models.Index(fields=['property', 'period_month'], name='tourism_lev_propert_b9c186_idx'), models.Index(fields=['is_remitted'], name='tourism_lev_is_remi_5e0355_idx')],
            },
        ),
    ]
