# Generated by Django 5.2.17 on 2026-10-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='modules',
            field=models.JSONField(blank=True, default=list, help_text='Enabled modules for this tenant'),
        ),
    ]
