# Generated by Django 5.2.17 on 2026-09-25 08:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('shared_users', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LOGIN_OK', 'Login Success'), ('LOGIN_FAIL', 'Login Failed'), ('LOGOUT', 'Logout'), ('PWD_RESET', 'Password Reset Requested'), ('PWD_CHG', 'Password Changed'), ('MFA_ON', 'MFA Enabled'), ('MFA_OFF', 'MFA Disabled'), ('TOKEN_REF', 'Token Refreshed'), ('PERM_DENY', 'Permission Denied'), ('ROLE_CHG', 'Role Changed'), ('MEMB_ADD', 'Membership Added'), ('MEMB_DEL', 'Membership Removed')], max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'auth audit log',
                'verbose_name_plural': 'auth audit logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('TADMIN', 'Tenant Administrator'), ('MGR', 'Manager'), ('FD', 'Front Desk'), ('HK', 'Housekeeper'), ('ACC', 'Accountant'), ('MNT', 'Maintenance'), ('AGT', 'Property Agent'), ('RO', 'Read Only')], max_length=6)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='For temporary access. Leave blank for permanent.', null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'user tenant membership',
                'verbose_name_plural': 'user tenant memberships',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255, verbose_name='address line 1'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, verbose_name='address line 2'),
        ),
        migrations.AddField(
            model_name='user',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='alternate phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='city / town'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='Malawi', max_length=100, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 9, 25, 8, 21, 28, 289481, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, help_text='e.g. Lilongwe, Blantyre, Mzuzu', max_length=100, verbose_name='district'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant the user last accessed — used for post-login redirect', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_users', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, help_text='Malawi National ID or passport number', max_length=50, verbose_name='national ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('ny', 'Chichewa')], default='en', max_length=5, verbose_name='preferred language'),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='Africa/Blantyre', max_length=50, verbose_name='timezone'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_platform_admin',
            field=models.BooleanField(default=False, help_text='Can manage all tenants. Bypasses tenant membership checks.', verbose_name='platform admin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Optional — common in Malawi naming conventions', max_length=150, verbose_name='middle name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='primary phone'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='shared_user_email_0d169c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_platform_admin', 'is_active'], name='shared_user_is_plat_647814_idx'),
        ),
        migrations.AddField(
            model_name='authauditlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_logs', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='authauditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usertenantmembership',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usertenantmembership',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_memberships', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='usertenantmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='authauditlog',
            index=models.Index(fields=['user', 'event_type', 'created_at'], name='shared_user_user_id_74d8c9_idx'),
        ),
        migrations.AddIndex(
            model_name='authauditlog',
            index=models.Index(fields=['tenant', 'created_at'], name='shared_user_tenant__ded588_idx'),
        ),
        migrations.AddIndex(
            model_name='authauditlog',
            index=models.Index(fields=['ip_address'], name='shared_user_ip_addr_658edd_idx'),
        ),
        migrations.AddIndex(
            model_name='authauditlog',
            index=models.Index(fields=['event_type', 'created_at'], name='shared_user_event_t_a4c60b_idx'),
        ),
        migrations.AddIndex(
            model_name='usertenantmembership',
            index=models.Index(fields=['user', 'tenant', 'is_active'], name='shared_user_user_id_975217_idx'),
        ),
        migrations.AddIndex(
            model_name='usertenantmembership',
            index=models.Index(fields=['tenant', 'role', 'is_active'], name='shared_user_tenant__2ac73d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usertenantmembership',
            unique_together={('user', 'tenant')},
        ),
    ]
