# Generated by Django 5.2.17 on 2026-10-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('shared_users', '0002_authauditlog_usertenantmembership_user_address_line1_and_more'),
        ('tenants', '0002_auto_20261001_064826'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False, help_text='Set to True after the user confirms an OTP', verbose_name='phone verified'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the successful OTP confirmation', null=True, verbose_name='phone verified at'),
        ),
        migrations.AlterField(
            model_name='authauditlog',
            name='event_type',
            field=models.CharField(choices=[('LOGIN_OK', 'Login Success'), ('LOGIN_FAIL', 'Login Failed'), ('LOGOUT', 'Logout'), ('PWD_RESET', 'Password Reset Requested'), ('PWD_CHG', 'Password Changed'), ('MFA_ON', 'MFA Enabled'), ('MFA_OFF', 'MFA Disabled'), ('TOKEN_REF', 'Token Refreshed'), ('PERM_DENY', 'Permission Denied'), ('ROLE_CHG', 'Role Changed'), ('MEMB_ADD', 'Membership Added'), ('MEMB_DEL', 'Membership Removed'), ('PHONE_OK', 'Phone Verified')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='shared_user_phone_471573_idx'),
        ),
    ]
