# Generated by Django 5.2.17 on 2026-09-19 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0001_initial'),
        ('people', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PART', 'Partially Paid'), ('PAID', 'Paid'), ('OVER', 'Overdue'), ('VOID', 'Void')], default='DRAFT', max_length=6)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='MWK', max_length=3)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='leases.lease')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rent_invoices', to='people.person')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rent_invoices', to='properties.unit')),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='RentInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_type', models.CharField(choices=[('RENT', 'Base Rent'), ('WATER', 'Water'), ('ELEC', 'Electricity'), ('GARB', 'Garbage'), ('SEC', 'Security'), ('SERV', 'Service Charge'), ('LATE', 'Late Fee'), ('OTHER', 'Other')], max_length=6)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('meter_reading_previous', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('meter_reading_current', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('meter_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='rent_invoicing.rentinvoice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('AIRTL', 'Airtel Money'), ('TNM', 'TNM Mpamba'), ('BANK', 'Bank Transfer'), ('CARD', 'Card'), ('CHQ', 'Cheque')], max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='MWK', max_length=3)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='rent_invoicing.rentinvoice')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='rentinvoice',
            index=models.Index(fields=['lease', 'status'], name='rent_invoic_lease_i_e0a254_idx'),
        ),
        migrations.AddIndex(
            model_name='rentinvoice',
            index=models.Index(fields=['due_date', 'status'], name='rent_invoic_due_dat_c442b2_idx'),
        ),
        migrations.AddIndex(
            model_name='rentinvoice',
            index=models.Index(fields=['tenant', 'status'], name='rent_invoic_tenant__65f359_idx'),
        ),
    ]
