# Generated by Django 5.2.17 on 2026-09-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0001_initial'),
        ('people', '0001_initial'),
        ('properties', '0003_alter_propertyimage_options_property_is_public_and_more'),
        ('rent_invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rentinvoice',
            index=models.Index(fields=['status', 'due_date'], name='rent_invoic_status_0fd336_idx'),
        ),
    ]
