# Generated by Django 5.2.17 on 2026-09-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('SETL', 'Settled'), ('VOID', 'Void')], default='OPEN', max_length=4)),
                ('currency', models.CharField(default='MWK', max_length=3)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FolioCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge_type', models.CharField(choices=[('ROOM', 'Room Charge'), ('FNB', 'Food & Beverage'), ('LAUN', 'Laundry'), ('MINI', 'Minibar'), ('ACT', 'Activity/Package'), ('MISC', 'Miscellaneous'), ('DISC', 'Discount')], max_length=5)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='MWK', max_length=3)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FolioPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('CASH_MWK', 'Cash (MWK)'), ('CASH_USD', 'Cash (USD)'), ('AIRTL', 'Airtel Money'), ('TNM', 'TNM Mpamba'), ('CARD', 'Card'), ('BANK', 'Bank Transfer')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='MWK', max_length=3)),
                ('reference', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
