# Generated by Django 5.2.17 on 2026-09-19 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folios', '0001_initial'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='folio',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='folio', to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='foliocharge',
            name='folio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='folios.folio'),
        ),
        migrations.AddField(
            model_name='foliocharge',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foliopayment',
            name='folio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='folios.folio'),
        ),
        migrations.AddField(
            model_name='foliopayment',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='folio',
            index=models.Index(fields=['status'], name='folios_foli_status_4d8821_idx'),
        ),
        migrations.AddIndex(
            model_name='foliocharge',
            index=models.Index(fields=['folio', 'charge_type'], name='folios_foli_folio_i_c872bd_idx'),
        ),
    ]
