# Generated by Django 5.2.17 on 2026-09-19 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('PLUMB', 'Plumbing'), ('ELEC', 'Electrical'), ('STRUC', 'Structural'), ('APPL', 'Appliance'), ('PEST', 'Pest Control'), ('GEN', 'General')], max_length=5)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MED', 'Medium'), ('HIGH', 'High'), ('EMERG', 'Emergency')], default='MED', max_length=5)),
                ('status', models.CharField(choices=[('SUBM', 'Submitted'), ('ACK', 'Acknowledged'), ('PROG', 'In Progress'), ('COMP', 'Completed'), ('VER', 'Verified'), ('CANC', 'Cancelled')], default='SUBM', max_length=4)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('assigned_to_name', models.CharField(blank=True, help_text='External contractor name (if not a platform user)', max_length=255)),
                ('parts_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('labour_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='people.person')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='properties.unit')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['unit', 'status'], name='maintenance_unit_id_3b432c_idx'), models.Index(fields=['status', 'priority'], name='maintenance_status_b5e015_idx'), models.Index(fields=['assigned_to', 'status'], name='maintenance_assigne_70195a_idx')],
            },
        ),
    ]
