# Generated by Django 5.2.17 on 2026-09-17 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('LEASE', 'Lease Agreement'), ('SALE', 'Sale Agreement'), ('ID', 'Identity Document'), ('INV', 'Invoice'), ('PHOTO', 'Property Photo'), ('MAINT', 'Maintenance Report'), ('OTHER', 'Other')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('file_size', models.PositiveIntegerField(help_text='Size in bytes')),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('object_id', models.PositiveIntegerField()),
                ('expiry_date', models.DateField(blank=True, help_text='Optional expiry date for time-limited documents', null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='documents_d_content_ba3031_idx'), models.Index(fields=['doc_type', 'is_current'], name='documents_d_doc_typ_a73e2d_idx')],
            },
        ),
    ]
