# Generated by Django 5.2.17 on 2026-09-19 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('people', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asking_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('minimum_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='MWK', max_length=3)),
                ('listing_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('LIST', 'Listed'), ('OFFER', 'Under Offer'), ('AGR', 'Agreement Signed'), ('COMP', 'Completed'), ('WDR', 'Withdrawn')], default='LIST', max_length=5)),
                ('description', models.TextField()),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='people.person')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_listings', to='properties.property')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_listings', to='properties.unit')),
            ],
            options={
                'ordering': ['-listing_date'],
            },
        ),
        migrations.CreateModel(
            name='SaleAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='MWK', max_length=3)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('deposit_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payment_type', models.CharField(choices=[('LUMP', 'Lump Sum'), ('INST', 'Installment Plan')], max_length=5)),
                ('completion_date', models.DateField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_agreements', to='people.person')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seller_agreements', to='people.person')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='agreement', to='sales.salelisting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='MWK', max_length=3)),
                ('status', models.CharField(choices=[('PEND', 'Pending'), ('ACC', 'Accepted'), ('REJ', 'Rejected'), ('CNTR', 'Countered'), ('WDR', 'Withdrawn')], default='PEND', max_length=5)),
                ('conditions', models.TextField(blank=True, help_text='e.g., mortgage approval, survey, board approval')),
                ('notes', models.TextField(blank=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_offers', to='people.person')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='sales.salelisting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commission_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='people.person')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='sales.saleagreement')),
            ],
            options={
                'unique_together': {('agreement', 'agent')},
            },
        ),
        migrations.CreateModel(
            name='SaleInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installment_number', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='sales.saleagreement')),
            ],
            options={
                'ordering': ['installment_number'],
                'unique_together': {('agreement', 'installment_number')},
            },
        ),
        migrations.AddIndex(
            model_name='salelisting',
            index=models.Index(fields=['status'], name='sales_salel_status_9425da_idx'),
        ),
    ]
