# Generated by Django 5.2.17 on 2026-09-25 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(choices=[('booking_confirmed', 'Booking Confirmed'), ('check_in_reminder', 'Check-in Reminder'), ('checkout_thanks', 'Check-out Thank You'), ('payment_receipt', 'Payment Receipt'), ('lease_renewal', 'Lease Renewal Reminder'), ('rent_due', 'Rent Due Reminder'), ('rent_overdue', 'Rent Overdue Notice'), ('maintenance_update', 'Maintenance Update'), ('welcome', 'Welcome Message')], max_length=30)),
                ('channel', models.CharField(choices=[('WA', 'WhatsApp'), ('EM', 'Email'), ('SMS', 'SMS')], max_length=3)),
                ('language', models.CharField(default='en', max_length=5)),
                ('name', models.CharField(help_text='WhatsApp template name (approved in Meta Business Manager) or email subject.', max_length=100)),
                ('body', models.TextField(help_text='Message body with {placeholders}. Available: {guest_name}, {property_name}, {reservation_number}, {check_in}, {check_out}, {amount}, {currency}, {balance}.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'ordering': ['event', 'channel'],
                'unique_together': {('event', 'channel', 'language')},
            },
        ),
        migrations.CreateModel(
            name='InboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_number', models.CharField(db_index=True, max_length=20)),
                ('body', models.TextField()),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('replied', models.BooleanField(default=False)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_messages', to='people.person')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['from_number', 'created_at'], name='communicati_from_nu_fc5c0a_idx'), models.Index(fields=['is_read'], name='communicati_is_read_74da06_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('WA', 'WhatsApp'), ('EM', 'Email'), ('SMS', 'SMS')], max_length=3)),
                ('event', models.CharField(max_length=30)),
                ('recipient', models.CharField(help_text='E.164 phone number or email address', max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body_preview', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PEND', 'Pending'), ('SENT', 'Sent'), ('DELIV', 'Delivered'), ('READ', 'Read'), ('FAIL', 'Failed')], default='PEND', max_length=5)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('reservation_id', models.PositiveIntegerField(blank=True, null=True)),
                ('folio_id', models.PositiveIntegerField(blank=True, null=True)),
                ('lease_id', models.PositiveIntegerField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='people.person')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['person', 'status'], name='communicati_person__e0e3ca_idx'), models.Index(fields=['channel', 'status'], name='communicati_channel_a870d0_idx'), models.Index(fields=['provider_message_id'], name='communicati_provide_2cc1a8_idx'), models.Index(fields=['event', 'created_at'], name='communicati_event_0a4066_idx')],
            },
        ),
    ]
