# Generated by Django 5.2.17 on 2026-09-19 01:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('people', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PEND', 'Pending Signature'), ('ACT', 'Active'), ('EXP', 'Expired'), ('TERM', 'Terminated'), ('REN', 'Renewed')], default='DRAFT', max_length=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('rent_free_until', models.DateField(blank=True, help_text='Rent-free period end date (common in commercial leases)', null=True)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('rent_currency', models.CharField(default='MWK', max_length=3)),
                ('payment_frequency', models.CharField(choices=[('MONTH', 'Monthly'), ('QTR', 'Quarterly'), ('YEAR', 'Annually')], default='MONTH', max_length=5)),
                ('payment_due_day', models.PositiveIntegerField(default=1, help_text='Day of month rent is due (1–28)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('escalation_percent', models.DecimalField(decimal_places=2, default=0, help_text='Annual rent increase percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit_received', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit_refunded', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grace_period_days', models.PositiveIntegerField(default=5)),
                ('late_fee_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('late_fee_fixed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('auto_renew', models.BooleanField(default=False)),
                ('renewal_notice_days', models.PositiveIntegerField(default=60)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leases', to='documents.document')),
                ('landlord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='landlord_leases', to='people.person')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='people.person')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='properties.unit')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='LeaseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rent_share', models.DecimalField(blank=True, decimal_places=2, help_text='If different from main rent', max_digits=12, null=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_units', to='leases.lease')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lease_units', to='properties.unit')),
            ],
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['unit', 'status'], name='leases_leas_unit_id_d203d6_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['tenant', 'status'], name='leases_leas_tenant__9c2189_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['end_date', 'status'], name='leases_leas_end_dat_697de7_idx'),
        ),
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='lease_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.CheckConstraint(condition=models.Q(('payment_due_day__gte', 1), ('payment_due_day__lte', 28)), name='lease_due_day_1_to_28'),
        ),
        migrations.AlterUniqueTogether(
            name='leaseunit',
            unique_together={('lease', 'unit')},
        ),
    ]
