# Generated by Django 5.2.17 on 2026-09-19 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayChanguTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('ref_id', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='MWK', max_length=3)),
                ('method', models.CharField(blank=True, choices=[('AIRTL', 'Airtel Money'), ('TNM', 'TNM Mpamba'), ('CARD', 'Card'), ('BANK', 'Bank Transfer')], max_length=6)),
                ('status', models.CharField(choices=[('INIT', 'Initiated'), ('PEND', 'Pending'), ('SUCC', 'Successful'), ('FAIL', 'Failed'), ('REF', 'Refunded')], default='INIT', max_length=4)),
                ('payer_mobile', models.CharField(blank=True, max_length=20)),
                ('payer_name', models.CharField(blank=True, max_length=255)),
                ('payer_email', models.EmailField(blank=True, max_length=254)),
                ('object_id', models.PositiveIntegerField()),
                ('verification_data', models.JSONField(blank=True, default=dict)),
                ('webhook_received_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['charge_id'], name='paychangu_p_charge__083e43_idx'), models.Index(fields=['status', 'created_at'], name='paychangu_p_status_736bc3_idx')],
            },
        ),
    ]
