# Generated by Django 5.2.17 on 2026-10-07 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('paychangu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paychangutransaction',
            name='charge_id',
            field=models.CharField(db_index=True, help_text='PayChangu-assigned transaction ID. Unique per transaction.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='paychangutransaction',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='paychangutransaction',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paychangutransaction',
            name='ref_id',
            field=models.CharField(blank=True, help_text='Our own reference (usually an invoice or folio number).', max_length=100),
        ),
        migrations.AlterField(
            model_name='paychangutransaction',
            name='verification_data',
            field=models.JSONField(blank=True, default=dict, help_text='Raw response from PayChangu verify_transaction.'),
        ),
        migrations.AddIndex(
            model_name='paychangutransaction',
            index=models.Index(fields=['content_type', 'object_id'], name='paychangu_p_content_4c562c_idx'),
        ),
    ]
