# Generated by Django 5.2.17 on 2026-09-18 09:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text='CSS icon class or Material Symbol name', max_length=50)),
                ('category', models.CharField(choices=[('ROOM', 'Room Feature'), ('PROPERTY', 'Property Feature'), ('SERVICE', 'Service')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('HOTEL', 'Hotel'), ('LODGE', 'Lodge'), ('RENTAL', 'Rental Building'), ('HOUSE', 'Standalone House'), ('MIXED', 'Mixed Use')], max_length=10)),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('NORTH', 'Northern'), ('CENTRAL', 'Central'), ('SOUTH', 'Southern')], max_length=10)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINT', 'Under Maintenance'), ('SOON', 'Coming Soon')], default='ACTIVE', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['property_type', 'status'], name='properties__propert_487234_idx'), models.Index(fields=['district', 'region'], name='properties__distric_3d6123_idx')],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_type', models.CharField(choices=[('ROOM', 'Hotel Room'), ('CHALET', 'Lodge Chalet'), ('APT', 'Apartment'), ('HOUSE', 'House'), ('BED', 'Bed (Dormitory)')], max_length=10)),
                ('identifier', models.CharField(help_text='e.g., "Room 101", "Chalet A"', max_length=50)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('capacity_adults', models.PositiveIntegerField(default=2)),
                ('capacity_children', models.PositiveIntegerField(default=0)),
                ('bed_count', models.PositiveIntegerField(default=1)),
                ('base_rate_mwk', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('base_rate_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('AVAIL', 'Available'), ('OCC', 'Occupied'), ('CLEAN', 'Cleaning'), ('MAINT', 'Maintenance'), ('BLOCK', 'Blocked'), ('SOLD', 'Sold')], default='AVAIL', max_length=6)),
                ('is_active', models.BooleanField(default=True)),
                ('amenities', models.ManyToManyField(blank=True, to='properties.amenity')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.property')),
            ],
            options={
                'verbose_name_plural': 'Units',
                'ordering': ['property', 'identifier'],
                'indexes': [models.Index(fields=['property', 'unit_type', 'status'], name='properties__propert_a97bd5_idx'), models.Index(fields=['status'], name='properties__status_e4b367_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('capacity_adults__gte', 1)), name='unit_capacity_adults_gte_1'), models.CheckConstraint(condition=models.Q(('bed_count__gte', 1)), name='unit_bed_count_gte_1')],
                'unique_together': {('property', 'identifier')},
            },
        ),
    ]
