# Generated by Django 5.2.17 on 2026-09-25 08:21

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/%Y/%m/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'verbose_name': 'property image',
                'verbose_name_plural': 'property images',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['property'], name='properties__propert_4e16ed_idx')],
            },
            bases=(apps.core.models.OptimizedImageMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StaffPropertyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'staff property assignment',
                'verbose_name_plural': 'staff property assignments',
                'indexes': [models.Index(fields=['user', 'is_active'], name='properties__user_id_e0b2be_idx'), models.Index(fields=['property', 'is_active'], name='properties__propert_db9ec0_idx')],
                'unique_together': {('user', 'property')},
            },
        ),
    ]
