# Generated by Django 5.2.17 on 2026-09-30 06:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_propertyimage_staffpropertyassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['order', '-is_cover', '-created_at'], 'verbose_name': 'property image', 'verbose_name_plural': 'property images'},
        ),
        migrations.AddField(
            model_name='property',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Show this property on the public listing page'),
        ),
        migrations.AddField(
            model_name='property',
            name='public_slug',
            field=models.SlugField(blank=True, help_text='URL-friendly name. Auto-generated if left blank.', max_length=255),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 9, 30, 6, 11, 46, 848482, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='is_cover',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.unit'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Show this unit on the public listing page'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_public', 'status'], name='properties__is_publ_3b189e_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['unit'], name='properties__unit_id_63b7be_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['is_public', 'status', 'unit_type'], name='properties__is_publ_66d949_idx'),
        ),
    ]
