# Generated by Django 5.2.17 on 2026-09-19 00:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('multiplier', models.DecimalField(blank=True, decimal_places=2, help_text='e.g., 1.50 = 50% increase over base rate', max_digits=4, null=True)),
                ('fixed_rate_mwk', models.DecimalField(blank=True, decimal_places=2, help_text='Overrides multiplier if set', max_digits=12, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_seasons', to='properties.property')),
            ],
            options={
                'ordering': ['start_date'],
                'indexes': [models.Index(fields=['property', 'start_date', 'end_date'], name='rates_prici_propert_92483a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='pricing_season_end_after_start')],
            },
        ),
        migrations.CreateModel(
            name='RatePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('policy', models.CharField(choices=[('FLEX', 'Flexible (Free cancellation 48h)'), ('NONREF', 'Non-Refundable'), ('BB', 'Bed & Breakfast'), ('AI', 'All-Inclusive')], max_length=6)),
                ('deposit_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of total required as deposit at booking', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cancellation_hours', models.PositiveIntegerField(default=48, help_text='Hours before check-in within which cancellation is free')),
                ('is_active', models.BooleanField(default=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_plans', to='properties.property')),
            ],
            options={
                'ordering': ['property', 'name'],
                'unique_together': {('property', 'name')},
            },
        ),
    ]
