# Generated by Django 5.2.17 on 2026-09-19 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCYBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=3)),
                ('branch', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('authorized_at', models.DateField(help_text='Date RBM authorization received')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcy_accounts', to='properties.property')),
            ],
            options={
                'verbose_name_plural': 'FCY Bank Accounts',
            },
        ),
        migrations.CreateModel(
            name='RBMReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('return_month', models.DateField(help_text='Month of return')),
                ('currency', models.CharField(max_length=3)),
                ('total_receipts', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_refunds', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_foreign_currency', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('submitted_to_rbm', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rbm_returns', to='properties.property')),
            ],
            options={
                'unique_together': {('property', 'return_month', 'currency')},
            },
        ),
    ]
