# Generated by Django 5.2.17 on 2026-10-02 16:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_auto_20261001_064826'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Stable identifier, e.g. "starter-monthly"', unique=True)),
                ('name', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('STARTER', 'Starter'), ('PRO', 'Professional'), ('ENT', 'Enterprise')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('features', models.JSONField(blank=True, default=list, help_text='Bullet list of feature strings shown on the pricing page')),
                ('price_mwk', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Optional — for foreign-owned tenants paying in USD', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('interval', models.CharField(choices=[('MONTH', 'Monthly'), ('YEAR', 'Annual')], default='MONTH', max_length=5)),
                ('max_properties', models.PositiveIntegerField(default=1, help_text='0 = unlimited')),
                ('max_units', models.PositiveIntegerField(default=10, help_text='0 = unlimited')),
                ('max_staff', models.PositiveIntegerField(default=3, help_text='0 = unlimited')),
                ('max_storage_mb', models.PositiveIntegerField(default=500, help_text='0 = unlimited')),
                ('includes_hospitality', models.BooleanField(default=True)),
                ('includes_rentals', models.BooleanField(default=False)),
                ('includes_sales', models.BooleanField(default=False)),
                ('includes_eis', models.BooleanField(default=True, help_text='MRA EIS invoicing — usually always included for compliance')),
                ('includes_whatsapp', models.BooleanField(default=True)),
                ('includes_priority_support', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True, help_text='Shown on the public pricing page')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('trial_days', models.PositiveIntegerField(default=30, help_text='Free trial length in days when a tenant subscribes to this plan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'price_mwk'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TRIAL', 'Free Trial'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past Due'), ('SUSP', 'Suspended'), ('CANC', 'Cancelled')], default='TRIAL', max_length=8)),
                ('trial_started_at', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('billing_phone', models.CharField(blank=True, max_length=20)),
                ('preferred_currency', models.CharField(choices=[('MWK', 'MWK'), ('USD', 'USD')], default='MWK', max_length=3)),
                ('last_payment_at', models.DateTimeField(blank=True, null=True)),
                ('last_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('consecutive_failed_payments', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.tenant')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.subscriptionplan')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='MWK', max_length=3)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PAID', 'Paid'), ('OVER', 'Overdue'), ('VOID', 'Void')], default='DRAFT', max_length=6)),
                ('paychangu_charge_id', models.CharField(blank=True, max_length=100)),
                ('paychangu_ref', models.CharField(blank=True, max_length=100)),
                ('mra_invoice_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='billing.subscription')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_invoices', to='tenants.tenant')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.subscriptionplan')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='MWK', max_length=3)),
                ('method', models.CharField(choices=[('AIRTL', 'Airtel Money'), ('TNM', 'TNM Mpamba'), ('CARD', 'Card'), ('BANK', 'Bank Transfer'), ('MANUAL', 'Manual (platform admin)')], max_length=6)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('paychangu_charge_id', models.CharField(blank=True, max_length=100)),
                ('payer_name', models.CharField(blank=True, max_length=255)),
                ('payer_phone', models.CharField(blank=True, max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.subscriptioninvoice')),
                ('received_by', models.ForeignKey(blank=True, help_text='Set only for manual payments by a platform admin', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CREATED', 'Subscription Created'), ('UP', 'Upgraded'), ('DOWN', 'Downgraded'), ('CANC', 'Cancelled'), ('SUSP', 'Suspended'), ('REACT', 'Reactivated'), ('TRIAL_EXT', 'Trial Extended')], max_length=10)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='billing.subscription')),
                ('from_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_from', to='billing.subscriptionplan')),
                ('to_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_to', to='billing.subscriptionplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='subscriptioninvoice',
            index=models.Index(fields=['status', 'due_date'], name='billing_sub_status_77f6df_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioninvoice',
            index=models.Index(fields=['tenant', 'status'], name='billing_sub_tenant__cd4c85_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioninvoice',
            index=models.Index(fields=['subscription', 'status'], name='billing_sub_subscri_0d2534_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'current_period_end'], name='billing_sub_status_684a21_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'trial_ends_at'], name='billing_sub_status_626969_idx'),
        ),
    ]
