# Generated by Django 5.2.17 on 2026-09-19 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HousekeepingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_type', models.CharField(choices=[('CO', 'Check-out Cleaning'), ('SO', 'Stayover Cleaning'), ('DEEP', 'Deep Cleaning'), ('INSP', 'Inspection')], max_length=5)),
                ('status', models.CharField(choices=[('PEND', 'Pending'), ('PROG', 'In Progress'), ('COMP', 'Completed'), ('INSP', 'Inspected'), ('SKIP', 'Skipped')], default='PEND', max_length=5)),
                ('priority', models.PositiveIntegerField(default=3, help_text='1 = Highest, 5 = Lowest')),
                ('notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='housekeeping_tasks', to=settings.AUTH_USER_MODEL)),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_tasks', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housekeeping_tasks', to='properties.unit')),
            ],
            options={
                'ordering': ['priority', 'created_at'],
                'indexes': [models.Index(fields=['status', 'assigned_to'], name='housekeepin_status_3cee57_idx'), models.Index(fields=['unit', 'status'], name='housekeepin_unit_id_19b8f0_idx')],
            },
        ),
    ]
