# Generated by Django 5.2.17 on 2026-09-17 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('id_type', models.CharField(blank=True, choices=[('NATID', 'Malawi National ID'), ('PASS', 'Passport'), ('DL', "Driver's License")], max_length=10)),
                ('id_number', models.CharField(blank=True, db_index=True, max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(default='Malawian', max_length=100)),
                ('phone_primary', models.CharField(db_index=True, max_length=20)),
                ('phone_secondary', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('ny', 'Chichewa')], default='en', max_length=2)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('blacklist_reason', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'People',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['phone_primary'], name='people_pers_phone_p_b280a0_idx'), models.Index(fields=['id_number'], name='people_pers_id_numb_1f4e14_idx'), models.Index(fields=['email'], name='people_pers_email_52ffb2_idx')],
            },
        ),
        migrations.CreateModel(
            name='PersonPropertyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('GUEST', 'Guest'), ('TENANT', 'Tenant'), ('BUYER', 'Buyer'), ('LANDLORD', 'Landlord'), ('OWNER', 'Property Owner'), ('STAFF', 'Staff Member')], max_length=10)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_roles', to='people.person')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_roles', to='properties.property')),
            ],
            options={
                'ordering': ['person', 'role'],
                'indexes': [models.Index(fields=['person', 'role'], name='people_pers_person__4d8cf8_idx'), models.Index(fields=['property', 'role'], name='people_pers_propert_83ffb3_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date')), ('end_date__isnull', True), _connector='OR'), name='person_role_end_after_start')],
            },
        ),
    ]
