# Generated by Django 5.2.17 on 2026-09-19 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForexRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_currency', models.CharField(default='MWK', max_length=3)),
                ('quote_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=14)),
                ('source', models.CharField(choices=[('PYX', 'pyxrate (auto)'), ('MAN', 'Manual Override'), ('BANK', 'Bank Rate')], default='PYX', max_length=4)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['quote_currency', 'effective_from'], name='forex_forex_quote_c_b5c8f2_idx')],
            },
        ),
        migrations.CreateModel(
            name='CurrencyLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(default='MWK', max_length=3)),
                ('locked_rate', models.DecimalField(decimal_places=6, max_digits=14)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='forex_curre_content_bd8563_idx')],
            },
        ),
    ]
