# Generated by Django 5.2.17 on 2026-09-19 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EISTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('terminal_code', models.CharField(max_length=50, unique=True)),
                ('terminal_activation_code', models.CharField(blank=True, help_text='TAC provided by MRA via email/SMS', max_length=100)),
                ('tin', models.CharField(help_text='Taxpayer Identification Number', max_length=20)),
                ('trading_name', models.CharField(max_length=255)),
                ('default_tax_office', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PEND', 'Pending Activation'), ('ACT', 'Active'), ('SUSP', 'Suspended'), ('OFF', 'Offline Mode')], default='PEND', max_length=5)),
                ('config_data', models.JSONField(blank=True, default=dict)),
                ('last_config_sync', models.DateTimeField(blank=True, null=True)),
                ('offline_signing_key', models.CharField(blank=True, help_text='Terminal-specific key for offline HMAC QR generation', max_length=255)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eis_terminals', to='properties.property')),
            ],
            options={
                'ordering': ['property', 'terminal_code'],
            },
        ),
        migrations.CreateModel(
            name='EISProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_code', models.CharField(max_length=50)),
                ('mra_product_code', models.CharField(blank=True, max_length=50)),
                ('mra_category_code', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('is_approved', models.BooleanField(default=False)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eis_products', to='properties.property')),
            ],
            options={
                'unique_together': {('property', 'internal_code')},
            },
        ),
        migrations.CreateModel(
            name='EISInvoiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('invoice_number', models.CharField(db_index=True, max_length=50)),
                ('mra_invoice_number', models.CharField(blank=True, max_length=50)),
                ('mra_validation_url', models.URLField(blank=True)),
                ('mra_qr_signature', models.TextField(blank=True, help_text='Signature converted to QR code')),
                ('mra_response_data', models.JSONField(blank=True, default=dict)),
                ('submission_status', models.CharField(choices=[('PEND', 'Pending Submission'), ('SUBM', 'Submitted to MRA'), ('VAL', 'Validated (MRA Invoice No Received)'), ('OFFQ', 'Queued Offline'), ('FAIL', 'Submission Failed'), ('DUP', 'Duplicate Invoice Number')], default='PEND', max_length=4)),
                ('offline_hmac_signature', models.TextField(blank=True)),
                ('offline_generated_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_logs', to='eis.eisterminal')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['invoice_number'], name='eis_eisinvo_invoice_17094c_idx'), models.Index(fields=['submission_status'], name='eis_eisinvo_submiss_7eacbf_idx'), models.Index(fields=['content_type', 'object_id'], name='eis_eisinvo_content_ace401_idx')],
            },
        ),
    ]
